name = "gemini-storybook-showcase"
compatibility_date = "2024-04-03"

type = "javascript"

[build]
command = "npm run build"
directory = ".next"  # 或者根据你的构建目录设置

[env.production]
workers_dev = false
route = "https://geministorybook.online/*"  # 将域名替换为您的实际域名
